name: Bug Report
description: Report a bug or issue with Image Tools
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to convert a HEIC file, the app crashes...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Upload file '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The image should convert successfully...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: The app shows an error message...
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: Chrome 120, Firefox 121, Safari 17
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: Windows 11, macOS 14, iOS 17
    validations:
      required: true

  - type: textarea
    id: file-info
    attributes:
      label: File Information (if applicable)
      description: Details about the file that caused the issue
      placeholder: |
        File format: HEIC
        File size: 5MB
        Dimensions: 4032x3024
    validations:
      required: false

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors from the browser console (F12 > Console)
      placeholder: Paste console errors here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: This started happening after...
    validations:
      required: false
